---
title: "R Notebook"
date: "Created: 2016-03-05 <br> Updated: `r Sys.Date()`"
output: html_notebook
---

When you want to make a change to the template, do so by going to:

Applications > Contents > Resources > resources > templates > r_markdown_notebook_osx.Rmd

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r load_packages, message=FALSE}
library(tidyverse)
data(mtcars)
```

SAS website: http://support.sas.com/documentation/cdl/en/proc/65145/HTML/default/viewer.htm#p0klmrp4k89pz0n1p72t0clpavyx.htm

Ungrouped mean and 95% CI

```{r}
mtcars %>% 
  filter(!is.na(mpg)) %>% 
  summarise(
    var = "mpg",
    n = n(),
    mean = mean(mpg),
    t_crit = qt(0.975, n - 1),
    sem = sd(mpg) / sqrt(n),
    lcl = mean - t_crit * sem,
    ucl = mean + t_crit * sem
  )

# Same as SAS
```

```{r}
mtcars %>% 
  group_by(cyl) %>% 
  bfuncs::freq_table()
```


-------------------------------------------------------------------------------

&nbsp;

#### Session Info:
```{r session_info, echo=FALSE}
sessionInfo()
```
