# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Numeric Last Observation Carried Forward
#'
#' @param x a numeric vector
#' @export
na_locf <- function(x) {
    .Call(`_bfuncs_na_locf`, x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_bfuncs_RcppExport_registerCCallable', PACKAGE = 'bfuncs')
})
